### ISSUE TITLE
Plugin does not ensure events are from interface items.

### ISSUE THREAD

**Issue by Cyborger1** [PolishToaster/patch-payment#2]
https://github.com/PolishToaster/patch-payment/blob/59c3967dde04d8112d634a98edb17aadf12e3fcf/src/main/java/com/patchpayment/PatchPaymentPlugin.java#L182

The plugin doesn't make sure the Check/Examine event is for an interface object. You can receive messages for unrelated IDs.

For example, examining a random fire here, it thinks it's a curry seed because it happens to share the same ID.
![curryfire](https://user-images.githubusercontent.com/45152844/100531112-4f626200-31c8-11eb-931a-26b467094f56.png)

**Comment by PolishToaster** [comment]
Thanks for the heads up, added a check to see if the item is within the inventory
